metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - memory
    - network
    - process
  enabled: true
  period: 10s
  processes: ['.*']
  cpu_ticks: false

- module: system
  metricsets: [socket]
  period: 500ms
  socket.reverse_lookup.enabled: true

- module: system
  period: 60s
  metricsets: [filesystem, fsstat]
  filters:
    - drop_event.when.regexp.mount_point: '^(/hostfs)?/(sys|cgroup|proc|dev|etc|host|var/lib/docker)($|/)'

- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock", "tcp://10.1.2.30:2375"]
  enabled: true
  period: 10s
      
output.elasticsearch:
  hosts: ["${ES_HOST_PORT}"]
  template.name: "metricbeat"
  template.path: "metricbeat.template.json"
  template.overwrite: false