filebeat:
  prospectors:
    - 
       input_type: log
       paths:
         - "/opt/openet/FW/fwHome/statistics/ServerCTE/*_high.stats.csv"
       document_type: stat
         
    - 
       input_type: log
       paths:
         - "/opt/openet/FW/fwHome/UnifiedLogging/*.log.csv"
       document_type: log
  
#    - 
#       input_type: log
#       paths:
#         - "/opt/openet/FW/fwHome/statistics/ServerCTE/*_Compositehigh.stats.csv"
#       document_type: cstat

#    - /opt/openet/FW/fwHome/log/*.log
# -- outputs
output:
  logstash:
    hosts: ["logstash:${BEAT_PORT:5044}"]    

logging:
  level: info
